package com.vjh0107.proxysynchronizer.enderchest.service

import com.vjh0107.proxysynchronizer.core.service.SyncPlayerService
import com.vjh0107.proxysynchronizer.enderchest.SyncPlayerEnderChestData

interface SyncPlayerEnderChestService : SyncPlayerService<SyncPlayerEnderChestData>