package com.vjh0107.proxysynchronizer.properties.repository

import com.vjh0107.proxysynchronizer.core.repository.SyncPlayerRepository
import com.vjh0107.proxysynchronizer.properties.SyncPlayerPropertiesData

interface SyncPlayerPropertiesRepository : SyncPlayerRepository<SyncPlayerPropertiesData>